### ISSUE TITLE
Falta o node_modules

### ISSUE THREAD

**Issue by PatricksPessoa** [lathne/Proffy-NLW2-Complete#1]
Pra rodar o localhost e poder ver o seu projeto depois de clonar, precisa do node_modules
Ele é facilmente instalado com o comando npm install nodemon -D no bash

**Comment by lathne** [comment]
Oi. Obrigado pelo feedback. Normalmente node_modules é muito grande, no meu caso o github não fez o upload por causa disso. Mas a grande sacada é que tudo o que você precisa pra desenvolver está listado no arquivo package.json, ele é o suficiente para saber de tudo que é necessário. Então, basta clonar o projeto e rodar no terminal npm install e assim tudo será instalado conforme listado no package.json, incluindo o que falta do node_modules. Um abraço!
